package com.github.countryman.profiles

object PresetCarriers {
    data class CarrierPreset(
        val name: String,
        val displayName: String,
        val region: String
    )

    val presets = listOf(
        CarrierPreset("中国移动", "China Mobile", "CN"),
        CarrierPreset("中国联通", "China Unicom", "CN"),
        CarrierPreset("中国电信", "China Telecom", "CN"),
        CarrierPreset("中国移动香港", "CMHK", "HK"),
        CarrierPreset("香港电讯", "HKT", "HK"),
        CarrierPreset("3香港", "3HK", "HK"),
        CarrierPreset("SmarTone", "SmarTone", "HK"),
        CarrierPreset("澳门电讯", "CTM", "MO"),
        CarrierPreset("3澳门", "3 Macau", "MO"),
        CarrierPreset("中华电信", "Chunghwa Telecom", "TW"),
        CarrierPreset("台湾大哥大", "Taiwan Mobile", "TW"),
        CarrierPreset("远传电信", "FarEasTone", "TW"),
        CarrierPreset("NTT docomo", "NTT docomo", "JP"),
        CarrierPreset("au", "au by KDDI", "JP"),
        CarrierPreset("Softbank", "Softbank", "JP"),
        CarrierPreset("Rakuten", "Rakuten Mobile", "JP"),
        CarrierPreset("SK Telecom", "SK Telecom", "KR"),
        CarrierPreset("KT", "KT Corporation", "KR"),
        CarrierPreset("LG U+", "LG U+", "KR"),
        CarrierPreset("AT&T", "AT&T", "US"),
        CarrierPreset("T-Mobile", "T-Mobile USA", "US"),
        CarrierPreset("Verizon", "Verizon", "US"),
        CarrierPreset("Sprint", "Sprint", "US"),
        CarrierPreset("EE", "EE", "GB"),
        CarrierPreset("O2", "O2 UK", "GB"),
        CarrierPreset("Three", "Three UK", "GB"),
        CarrierPreset("Vodafone", "Vodafone UK", "GB"),
        CarrierPreset("Singtel", "Singtel", "SG"),
        CarrierPreset("StarHub", "StarHub", "SG"),
        CarrierPreset("M1", "M1", "SG"),
        CarrierPreset("Maxis", "Maxis", "MY"),
        CarrierPreset("Celcom", "Celcom", "MY"),
        CarrierPreset("Digi", "Digi", "MY"),
        CarrierPreset("U Mobile", "U Mobile", "MY"),
        CarrierPreset("AIS", "AIS", "TH"),
        CarrierPreset("DTAC", "DTAC", "TH"),
        CarrierPreset("True Move H", "True Move H", "TH"),
        CarrierPreset("Viettel", "Viettel Mobile", "VN"),
        CarrierPreset("Vinaphone", "Vinaphone", "VN"),
        CarrierPreset("Mobifone", "Mobifone", "VN"),
        CarrierPreset("Telkomsel", "Telkomsel", "ID"),
        CarrierPreset("Indosat", "Indosat Ooredoo", "ID"),
        CarrierPreset("XL Axiata", "XL Axiata", "ID"),
        CarrierPreset("Globe", "Globe Telecom", "PH"),
        CarrierPreset("Smart", "Smart Communications", "PH"),
        CarrierPreset("DITO", "DITO Telecommunity", "PH"),
        CarrierPreset("Jio", "Reliance Jio", "IN"),
        CarrierPreset("Airtel", "Bharti Airtel", "IN"),
        CarrierPreset("Vi", "Vodafone Idea", "IN"),
        CarrierPreset("Telstra", "Telstra", "AU"),
        CarrierPreset("Optus", "Optus", "AU"),
        CarrierPreset("Vodafone", "Vodafone AU", "AU"),
        CarrierPreset("Bell", "Bell Mobility", "CA"),
        CarrierPreset("Rogers", "Rogers Wireless", "CA"),
        CarrierPreset("Telus", "Telus Mobility", "CA"),
        CarrierPreset("Telekom", "T-Mobile DE", "DE"),
        CarrierPreset("Vodafone", "Vodafone DE", "DE"),
        CarrierPreset("O2", "O2 DE", "DE"),
        CarrierPreset("Orange", "Orange FR", "FR"),
        CarrierPreset("SFR", "SFR", "FR"),
        CarrierPreset("Free", "Free Mobile", "FR"),
        CarrierPreset("Bouygues", "Bouygues Telecom", "FR"),
        CarrierPreset("TIM", "Telecom Italia", "IT"),
        CarrierPreset("Vodafone", "Vodafone IT", "IT"),
        CarrierPreset("Wind Tre", "Wind Tre", "IT"),
        CarrierPreset("Movistar", "Movistar", "ES"),
        CarrierPreset("Vodafone", "Vodafone ES", "ES"),
        CarrierPreset("Orange", "Orange ES", "ES"),
        CarrierPreset("MTS", "MTS", "RU"),
        CarrierPreset("MegaFon", "MegaFon", "RU"),
        CarrierPreset("Beeline", "Beeline", "RU"),
        CarrierPreset("Vivo", "Vivo", "BR"),
        CarrierPreset("Claro", "Claro", "BR"),
        CarrierPreset("TIM", "TIM Brasil", "BR")
    )
}
